language: objective-c
matrix:
  include:
    - osx_image: xcode7.3
    - osx_image: xcode8
install:
  - gem install cocoapods -v 1.1.1
before_script:
  - rm -rf ~/Library/Developer/Xcode/DerivedData
script:
  # Test that the framework can be installed and built, and passes all unit tests
  - pod update
  - carthage update
  - pod lib lint
  - xcodebuild -workspace 'BMSCore.xcworkspace' -scheme 'BMSCore iOS' clean build CODE_SIGN_IDENTITY= CODE_SIGNING_REQUIRED=NO
  - xcodebuild -workspace 'BMSCore.xcworkspace' -scheme 'BMSCore watchOS' clean build CODE_SIGN_IDENTITY= CODE_SIGNING_REQUIRED=NO
  - travis_retry xcodebuild -workspace 'BMSCore.xcworkspace' test -scheme 'BMSCore Tests' -destination 'platform=iOS Simulator,name=iPhone 6'

  # When merging to the master branch, we check if the version specified in the .podspec does not already exist as a git tag.
  # If the version does not exist yet, we add a git tag for this new version and publish to Cocoapods.
  - if [ "${TRAVIS_PULL_REQUEST}" = "false" ] && [ "${TRAVIS_BRANCH}" = "master" ] && [[ "${TRAVIS_JOB_NUMBER}" = *".2"* ]]; then
        cd ~/Documents;
        git clone https://ibm-bluemix-mobile-services:${GITHUB_TOKEN}@github.com/ibm-bluemix-mobile-services/bms-clientsdk-swift-core.git;
        cd bms-clientsdk-swift-core;
        git remote rm origin;
        git remote add origin https://ibm-bluemix-mobile-services:${GITHUB_TOKEN}@github.com/ibm-bluemix-mobile-services/bms-clientsdk-swift-core.git;
        version=$(grep -o 'version.*=.*[0-9]' BMSCore.podspec | cut -f 2 -d "'");
        git fetch --tags;
        if [[ ! "$(git tag)" =~ "${version}" ]]; then
          echo "Publishing new version ${version} ";
          git tag $version;
          git push origin --tags;
          pod trunk push;
        fi
      fi